version: '3'
services:
  flask_backend:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - 5000:5000
    depends_on:
      - mongodb
      - redis
    networks:
      - mynetwork

  nginx_frontend:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - mynetwork

volumes:
  mongodb_data:

networks:
  mynetwork: