# 建立 Flask 後端的 Docker 階段
FROM python:3.9

WORKDIR /app

# 將 Flask 後端程式碼複製到容器中
COPY ./backend .

# 安裝相依套件
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
# RUN pip install --no-cache-dir -U Flask
# 開放 Flask 伺服器的埠號
EXPOSE 5000

# 執行 Flask 伺服器
CMD ["python", "app.py", "run", "--host", "0.0.0.0", "--port", "5000"]